# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 03:54
from __future__ import unicode_literals

from django.db import migrations, models

from django.utils.text import slugify

SLUG_LENGTH = 763

class Migration(migrations.Migration):
    def add_slug_data(apps, schema_editor):
        NewsLink = apps.get_model('organizer', 'NewsLink')
        query = NewsLink.objects.all()
        for newslink in query:
            expected_slug = slugify(newslink.title)
            rivals = (NewsLink.objects.filter(startup=newslink.startup, slug__startswith=expected_slug).count())
            if rivals > 0:
                str_len = SLUG_LENGTH - len(str(rivals))
                newslink.slug = "{}-{}".format(expected_slug[:str_len - 1], rivals + 1)
            else:
                newslink.slug = expected_slug



    dependencies = [
        ('organizer', '0005_newslink_data'),
    ]

    operations = [
        migrations.AddField(model_name='newslink', name='slug', field=models.SlugField(max_length=SLUG_LENGTH, default=''), )
    ]
